// <auto-generated />
using System;
using Booking.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booking.Persistence.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20190602122207_ChangeCapacityNumberOfPersonDataType")]
    partial class ChangeCapacityNumberOfPersonDataType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Booking.Domain.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoomID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(40);

                    b.Property<int>("Capacity");

                    b.Property<string>("Description")
                        .HasMaxLength(40);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<byte[]>("RoomImage")
                        .HasColumnType("image");

                    b.Property<bool?>("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Booking.Domain.RoomRental", b =>
                {
                    b.Property<int>("RoomRentalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoomRentalID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateFrom")
                        .IsRequired();

                    b.Property<DateTime?>("DateTo")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NumberOfPerson");

                    b.Property<int>("RoomId");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("RoomRentalID");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomRentals");
                });

            modelBuilder.Entity("Booking.Domain.RoomRental", b =>
                {
                    b.HasOne("Booking.Domain.Room", "Room")
                        .WithMany("RoomRentals")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
